# Project Information
site_name: Philippines vACC Knowledge Base
site_url: 
site_author: Kenzo Tayko, Emilio Perez & Michael Uy
edit_uri: edit/main/docs/
copyright: Copyright © 2022 Philippines vACC. All rights reserved. The information contained on this website is for flight simulation purposes only.

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - mike

  
# Configuration
theme:
  language: en
  name: material
  font:
    text: Mulish
    
  logo: assets/img/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking    
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  favicon: assets/img/favicon.ico

  palette:
    - scheme: vatphil
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: 
      accent: amber
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: amber
      accent: amber   

  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de 




extra_css:
  - stylesheets/vatphil.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/vatsimph
    - icon: fontawesome/brands/facebook 
      link: https://facebook.com/philippinesvacc
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/vatphil
    - icon: material/home
      link: https://vatphil.com
      name: Philippines vACC Main Website

  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.


  version:
    provider: mike


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/notkenzotayko/vatphil-knowledgebase
repo_name: vatsimph/knowledgebase
